/**
 * Canonical AI Service Interfaces & Response Contracts
 * Isolates model providers and enforces strict structured output.
 */

export type AIProvider = "gemini" | "openai" | "claude" | "mock";

export interface AIServiceConfig {
  provider: AIProvider;
  modelName: string;
  apiKey?: string;
  temperature?: number;
  maxTokens?: number;
}

/**
 * Pedagogical Step Explanation (Zod-validated structured response)
 */
export interface StepExplanation {
  summary: string;              // 1-2 sentence description of what physically occurred in this step
  why: string;                  // Algorithmic rationale linking the code statement to variable changes
  changes: string[];            // List of specific state transitions observed (e.g. "curr advanced to Node(20)")
  dataStructureInsight?: string;// Structural insight regarding linked list / array / BST mutations
  learningPoint: string;        // Core conceptual takeaway or pattern reminder for the student
}

/**
 * Input request payload sent to /api/ai/explain-step
 */
export interface ExplainStepRequest {
  stepIndex: number;
  totalSteps: number;
  sourceCode: string;
  currentLineCode?: string;
  context: BoundedTraceContext;
}

/**
 * Interactive Tutor Response (Zod-validated structured response)
 */
export interface TutorResponse {
  answer: string;              // Pedagogical explanation answering the student's question
  evidence: string[];          // Observed trace evidence (specific lines, variables, or diffs)
  learningPoint?: string;      // Conceptual takeaway, pattern, or invariant reminder
}

/**
 * Single message in the multi-turn Tutor conversation
 */
export interface TutorMessage {
  id: string;
  role: "user" | "assistant";
  text: string;
  timestamp: number;
  stepIndex: number;           // Step index at the time the message was created
  responseObj?: TutorResponse; // Structured tutor response when role === "assistant"
}

/**
 * Input request payload sent to /api/ai/tutor
 */
export interface TutorRequest {
  question: string;
  stepIndex: number;
  totalSteps: number;
  sourceCode: string;
  history: Array<{
    role: "user" | "assistant";
    text: string;
  }>;
  context: BoundedTraceContext;
}

/**
 * Bounded Trace Context generated by traceContextBuilder
 */
export interface BoundedTraceContext {
  stepIndex: number;
  line: number;
  eventType: string;
  description: string;
  activeLineSource?: string;
  currentScope: Record<string, string>;
  previousScope?: Record<string, string>;
  diff: StateDiff;
  callStackDepth: number;
  callStackTop?: string;
  heapSummary?: string[];
  activePointers: string[];
  stdout?: string[];
  newStdout?: string[];
  exception?: {
    type: string;
    message: string;
  } | null;
  detectedStructureType?: string;
  isTruncated: boolean;
  truncationReason?: string;
}

export interface StateDiff {
  variablesAdded: Array<{ name: string; value: string }>;
  variablesRemoved: Array<{ name: string; previousValue: string }>;
  variablesChanged: Array<{ name: string; from: string; to: string }>;
  pointersMoved: Array<{ name: string; from?: string; to?: string }>;
  heapObjectsCreated: string[];
  heapFieldsChanged: Array<{ objectId: string; field: string; from: string; to: string }>;
  heapReferencesChanged: Array<{ objectId: string; pointer: string; from: string; to: string }>;
  stdoutAdded: string[];
  exceptionOccurred: boolean;
}

/**
 * Phase 6B & 6C: Big-O & Complexity Analysis Types
 */
export type ComplexityClass =
  | "O(1)"
  | "O(log n)"
  | "O(n)"
  | "O(n log n)"
  | "O(n²)"
  | "O(n³)"
  | "exponential"
  | "unknown";

export type ComplexityConfidence = "high" | "medium" | "low";

export type ComplexityEvidenceKind =
  | "loop_nesting"
  | "line_repetition"
  | "recursion"
  | "halving"
  | "heap_growth"
  | "trace_boundary";

export interface ComplexityEvidenceItem {
  kind: ComplexityEvidenceKind;
  description: string;
  sourceLine?: number;
  observedValue?: string | number;
}

export interface DeterministicComplexityMetrics {
  totalSteps: number;
  totalOperations: number;
  maxCallStackDepth: number;
  lineExecutionCounts: Record<number, number>;
  maxLineExecutionCount: number;
  maxLoopNesting: number;
  isRecursive: boolean;
  recursionDepth: number;
  detectedStructures: string[];
  peakHeapObjects: number;
  observedTimeHeuristic: ComplexityClass;
  observedSpaceHeuristic: ComplexityClass;
  evidenceItems: ComplexityEvidenceItem[];
}

export interface ComplexityAnalysis {
  timeComplexity: ComplexityClass;
  spaceComplexity: ComplexityClass;
  confidence: ComplexityConfidence;
  summary: string;
  why: string;
  evidenceExplanation: string[];
  educationalTakeaway: string;
  limitations: string[];
  evidenceItems: ComplexityEvidenceItem[];
  metrics: DeterministicComplexityMetrics;
}

export interface ComplexityRequest {
  executionId: string;
  sourceCode: string;
  metrics: DeterministicComplexityMetrics;
  detectedStructures: string[];
  status: string;
}
